[package]
name = "maestro-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
serial_test = "3.1.1"
chrono = { version = "0.4.38", features = ["serde"] }
